// Tend — Realistic Vancouver-based mock data
import type {
  Elder,
  Helper,
  Booking,
  Review,
  MessageThread,
  ServiceType,
} from '../types';

// ─── Service Labels ─────────────────────────────────────────────────────────
export const serviceLabels: Record<ServiceType, string> = {
  companionship: 'Companionship',
  groceries: 'Groceries',
  meal_prep: 'Meal Prep',
  errands: 'Errands',
  housekeeping: 'Housekeeping',
  transportation: 'Transport',
  garden: 'Gardening',
  tech_help: 'Tech Help',
  pet_care: 'Pet Care',
  overnight: 'Overnight',
};

// ─── Elders ─────────────────────────────────────────────────────────────────
export const elders: Elder[] = [
  {
    id: 'elder-1',
    firstName: 'Margaret',
    lastName: 'Chen',
    city: 'Vancouver',
    postalCode: 'V6K 1A1',
    rating: 4.9,
    totalReviews: 12,
    memberSince: '2025-03-15',
    bio: 'Retired school teacher who loves reading, gardening, and walks along the seawall. Looking for friendly companionship and occasional help with groceries.',
    needs: ['companionship', 'groceries', 'garden'],
    preferences: { genderPreference: 'female', ageGroupPreference: '30-40' },
    favoriteHelpers: ['helper-1', 'helper-3'],
  },
  {
    id: 'elder-2',
    firstName: 'Robert',
    lastName: 'Patterson',
    city: 'North Vancouver',
    postalCode: 'V7L 1B7',
    rating: 4.7,
    totalReviews: 8,
    memberSince: '2025-06-01',
    bio: 'Retired engineer. Enjoy chess, woodworking, and watching the Canucks. Need help with transportation to medical appointments and some meal preparation.',
    needs: ['transportation', 'meal_prep', 'tech_help'],
    preferences: { genderPreference: 'no_preference', ageGroupPreference: 'no_preference' },
    favoriteHelpers: ['helper-2'],
  },
  {
    id: 'elder-3',
    firstName: 'Dorothy',
    lastName: 'Singh',
    city: 'Burnaby',
    postalCode: 'V5H 3Z7',
    rating: 5.0,
    totalReviews: 4,
    memberSince: '2025-11-20',
    bio: 'Widowed grandmother of five. I love cooking Punjabi food and would enjoy someone to share tea and conversation with. Need help keeping the house tidy.',
    needs: ['companionship', 'housekeeping', 'errands'],
    preferences: { genderPreference: 'female', ageGroupPreference: '20-30' },
    favoriteHelpers: ['helper-3', 'helper-5'],
  },
];

// ─── Helpers ────────────────────────────────────────────────────────────────
export const helpers: Helper[] = [
  {
    id: 'helper-1',
    firstName: 'Sarah',
    lastName: 'Williams',
    gender: 'female',
    ageGroup: '30-40',
    city: 'Vancouver',
    postalCode: 'V6B 2W9',
    distance: 2.3,
    bio: 'Former care aide with 5 years of experience in long-term care facilities. I genuinely love spending time with elders and hearing their stories. Fluent in English and French. I have my own car and am happy to drive to appointments, pick up groceries, or just sit and chat over tea.',
    headline: 'Experienced care aide who loves a good cup of tea',
    services: [
      { service: 'companionship', ratePerHour: 28 },
      { service: 'groceries', ratePerHour: 25 },
      { service: 'meal_prep', ratePerHour: 30 },
      { service: 'transportation', ratePerHour: 30 },
    ],
    specialSkills: ['First Aid Certified', 'Dementia Care', 'Light Physiotherapy'],
    hasCar: true,
    languages: ['English', 'French'],
    verificationLevel: 'premium',
    idVerified: true,
    backgroundChecked: true,
    referencesVerified: 3,
    rating: 4.9,
    totalReviews: 47,
    repeatClients: 8,
    completedBookings: 124,
    responseTime: '~30 min',
    memberSince: '2024-11-01',
    favoriteElders: ['elder-1'],
    availability: {
      monday: true, tuesday: true, wednesday: true,
      thursday: true, friday: true, saturday: false, sunday: false,
    },
  },
  {
    id: 'helper-2',
    firstName: 'James',
    lastName: 'Okafor',
    gender: 'male',
    ageGroup: '20-30',
    city: 'North Vancouver',
    postalCode: 'V7M 2K1',
    distance: 4.1,
    bio: 'Nursing student at BCIT with a passion for elder care. I grew up helping my grandparents in Nigeria and understand the value of patience, respect, and genuine connection. Available evenings and weekends.',
    headline: 'Nursing student with a heart for elders',
    services: [
      { service: 'companionship', ratePerHour: 24 },
      { service: 'errands', ratePerHour: 22 },
      { service: 'tech_help', ratePerHour: 20 },
      { service: 'transportation', ratePerHour: 26 },
    ],
    specialSkills: ['CPR Certified', 'Medication Reminders', 'Tech Troubleshooting'],
    hasCar: true,
    languages: ['English', 'Igbo'],
    verificationLevel: 'enhanced',
    idVerified: true,
    backgroundChecked: true,
    referencesVerified: 2,
    rating: 4.8,
    totalReviews: 23,
    repeatClients: 4,
    completedBookings: 56,
    responseTime: '~1 hour',
    memberSince: '2025-02-14',
    favoriteElders: ['elder-2'],
    availability: {
      monday: false, tuesday: false, wednesday: true,
      thursday: true, friday: true, saturday: true, sunday: true,
    },
  },
  {
    id: 'helper-3',
    firstName: 'Priya',
    lastName: 'Sharma',
    gender: 'female',
    ageGroup: '40-50',
    city: 'Burnaby',
    postalCode: 'V5C 5M9',
    distance: 5.8,
    bio: 'Retired physiotherapist and mother of two. I speak Hindi, Punjabi, and English fluently. Specialising in gentle companionship, meal preparation (Indian and Western cuisine), and light housekeeping. I believe in treating every elder like family.',
    headline: 'Retired physiotherapist & home-cooked meals specialist',
    services: [
      { service: 'companionship', ratePerHour: 30 },
      { service: 'meal_prep', ratePerHour: 32 },
      { service: 'housekeeping', ratePerHour: 28 },
      { service: 'garden', ratePerHour: 25 },
    ],
    specialSkills: ['Physiotherapy', 'Indian Cuisine', 'Yoga Instruction'],
    hasCar: true,
    languages: ['English', 'Hindi', 'Punjabi'],
    verificationLevel: 'premium',
    idVerified: true,
    backgroundChecked: true,
    referencesVerified: 4,
    rating: 5.0,
    totalReviews: 31,
    repeatClients: 11,
    completedBookings: 89,
    responseTime: '~45 min',
    memberSince: '2024-09-10',
    favoriteElders: ['elder-1', 'elder-3'],
    availability: {
      monday: true, tuesday: true, wednesday: false,
      thursday: true, friday: true, saturday: true, sunday: false,
    },
  },
  {
    id: 'helper-4',
    firstName: 'Lucas',
    lastName: 'Tremblay',
    gender: 'male',
    ageGroup: '20-30',
    city: 'Vancouver',
    postalCode: 'V6E 1M6',
    distance: 1.5,
    bio: 'UBC kinesiology graduate and certified personal trainer. I help seniors stay active with gentle exercise routines, walks, and mobility work. Also happy to help with pet care and tech setup.',
    headline: 'Kinesiology grad keeping seniors active & mobile',
    services: [
      { service: 'companionship', ratePerHour: 26 },
      { service: 'pet_care', ratePerHour: 24 },
      { service: 'tech_help', ratePerHour: 22 },
      { service: 'errands', ratePerHour: 24 },
    ],
    specialSkills: ['Exercise Science', 'Fall Prevention', 'Pet First Aid'],
    hasCar: false,
    languages: ['English', 'French'],
    verificationLevel: 'enhanced',
    idVerified: true,
    backgroundChecked: true,
    referencesVerified: 1,
    rating: 4.7,
    totalReviews: 15,
    repeatClients: 3,
    completedBookings: 34,
    responseTime: '~2 hours',
    memberSince: '2025-05-22',
    favoriteElders: [],
    availability: {
      monday: true, tuesday: false, wednesday: true,
      thursday: false, friday: true, saturday: true, sunday: true,
    },
  },
  {
    id: 'helper-5',
    firstName: 'Mei',
    lastName: 'Liu',
    gender: 'female',
    ageGroup: '30-40',
    city: 'Richmond',
    postalCode: 'V7A 1N6',
    distance: 8.2,
    bio: 'Fluent in Mandarin, Cantonese, and English. Former home care worker with certifications in senior care. I love doing overnight stays for elders who need extra peace of mind. Patient, warm, and always on time.',
    headline: 'Trilingual caregiver with overnight availability',
    services: [
      { service: 'companionship', ratePerHour: 27 },
      { service: 'overnight', ratePerHour: 22 },
      { service: 'meal_prep', ratePerHour: 28 },
      { service: 'housekeeping', ratePerHour: 26 },
    ],
    specialSkills: ['Overnight Care', 'Chinese Cuisine', 'Medication Management'],
    hasCar: true,
    languages: ['English', 'Mandarin', 'Cantonese'],
    verificationLevel: 'premium',
    idVerified: true,
    backgroundChecked: true,
    referencesVerified: 3,
    rating: 4.9,
    totalReviews: 38,
    repeatClients: 6,
    completedBookings: 102,
    responseTime: '~20 min',
    memberSince: '2024-08-05',
    favoriteElders: ['elder-3'],
    availability: {
      monday: true, tuesday: true, wednesday: true,
      thursday: true, friday: true, saturday: true, sunday: true,
    },
  },
];

// ─── Bookings ───────────────────────────────────────────────────────────────
export const bookings: Booking[] = [
  {
    id: 'booking-1',
    elderId: 'elder-1',
    elderName: 'Margaret Chen',
    helperId: 'helper-1',
    helperName: 'Sarah Williams',
    service: 'companionship',
    date: '2026-03-05',
    startTime: '10:00',
    endTime: '12:00',
    duration: 2,
    totalCost: 56,
    status: 'confirmed',
    notes: 'Walk along Kitsilano Beach if weather permits.',
    createdAt: '2026-02-28T14:00:00Z',
  },
  {
    id: 'booking-2',
    elderId: 'elder-2',
    elderName: 'Robert Patterson',
    helperId: 'helper-2',
    helperName: 'James Okafor',
    service: 'transportation',
    date: '2026-03-04',
    startTime: '09:00',
    endTime: '11:00',
    duration: 2,
    totalCost: 52,
    status: 'active',
    notes: 'Drive to Lions Gate Hospital for physio appointment.',
    createdAt: '2026-03-01T09:30:00Z',
  },
  {
    id: 'booking-3',
    elderId: 'elder-3',
    elderName: 'Dorothy Singh',
    helperId: 'helper-3',
    helperName: 'Priya Sharma',
    service: 'meal_prep',
    date: '2026-03-06',
    startTime: '14:00',
    endTime: '17:00',
    duration: 3,
    totalCost: 96,
    status: 'pending',
    notes: 'Prepare dal, rice, and roti for the week.',
    createdAt: '2026-03-02T16:45:00Z',
  },
  {
    id: 'booking-4',
    elderId: 'elder-1',
    elderName: 'Margaret Chen',
    helperId: 'helper-3',
    helperName: 'Priya Sharma',
    service: 'garden',
    date: '2026-02-20',
    startTime: '10:00',
    endTime: '13:00',
    duration: 3,
    totalCost: 75,
    status: 'completed',
    elderRating: 5,
    helperRating: 5,
    createdAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'booking-5',
    elderId: 'elder-2',
    elderName: 'Robert Patterson',
    helperId: 'helper-4',
    helperName: 'Lucas Tremblay',
    service: 'tech_help',
    date: '2026-02-25',
    startTime: '15:00',
    endTime: '16:30',
    duration: 1.5,
    totalCost: 33,
    status: 'completed',
    elderRating: 5,
    helperRating: 4,
    createdAt: '2026-02-20T11:20:00Z',
  },
  {
    id: 'booking-6',
    elderId: 'elder-3',
    elderName: 'Dorothy Singh',
    helperId: 'helper-5',
    helperName: 'Mei Liu',
    service: 'overnight',
    date: '2026-03-07',
    startTime: '20:00',
    endTime: '08:00',
    duration: 12,
    totalCost: 264,
    status: 'confirmed',
    notes: 'Dorothy had a fall last week, family wants overnight company.',
    createdAt: '2026-03-03T08:00:00Z',
  },
  {
    id: 'booking-7',
    elderId: 'elder-1',
    elderName: 'Margaret Chen',
    helperId: 'helper-1',
    helperName: 'Sarah Williams',
    service: 'groceries',
    date: '2026-02-10',
    startTime: '11:00',
    endTime: '12:30',
    duration: 1.5,
    totalCost: 37.5,
    status: 'completed',
    elderRating: 5,
    helperRating: 5,
    createdAt: '2026-02-05T13:00:00Z',
  },
  {
    id: 'booking-8',
    elderId: 'elder-2',
    elderName: 'Robert Patterson',
    helperId: 'helper-2',
    helperName: 'James Okafor',
    service: 'companionship',
    date: '2026-03-10',
    startTime: '14:00',
    endTime: '16:00',
    duration: 2,
    totalCost: 48,
    status: 'pending',
    notes: 'Chess afternoon — Robert will provide the board.',
    createdAt: '2026-03-03T10:15:00Z',
  },
];

// ─── Reviews ────────────────────────────────────────────────────────────────
export const reviews: Review[] = [
  {
    id: 'review-1',
    fromUserId: 'elder-1',
    fromUserName: 'Margaret C.',
    fromUserRole: 'elder',
    toUserId: 'helper-1',
    rating: 5,
    comment: 'Sarah is an absolute gem. She walked with me along the seawall and we had the most wonderful conversation. Already booked her again!',
    service: 'companionship',
    date: '2026-02-22',
  },
  {
    id: 'review-2',
    fromUserId: 'helper-1',
    fromUserName: 'Sarah W.',
    fromUserRole: 'helper',
    toUserId: 'elder-1',
    rating: 5,
    comment: 'Margaret is a delight. She shared stories about teaching in Hong Kong and made me the best chrysanthemum tea.',
    service: 'companionship',
    date: '2026-02-22',
  },
  {
    id: 'review-3',
    fromUserId: 'elder-2',
    fromUserName: 'Robert P.',
    fromUserRole: 'elder',
    toUserId: 'helper-2',
    rating: 5,
    comment: 'James was punctual and very careful driving. He even helped me into the clinic. Top-notch young man.',
    service: 'transportation',
    date: '2026-02-18',
  },
  {
    id: 'review-4',
    fromUserId: 'elder-3',
    fromUserName: 'Dorothy S.',
    fromUserRole: 'elder',
    toUserId: 'helper-3',
    rating: 5,
    comment: 'Priya made the most delicious dal I have had in years. She reminds me of my daughter. We cooked together and I taught her my roti recipe!',
    service: 'meal_prep',
    date: '2026-02-21',
  },
  {
    id: 'review-5',
    fromUserId: 'elder-2',
    fromUserName: 'Robert P.',
    fromUserRole: 'elder',
    toUserId: 'helper-4',
    rating: 5,
    comment: 'Lucas set up my new iPad and was incredibly patient explaining everything. Now I can video call my grandkids!',
    service: 'tech_help',
    date: '2026-02-26',
  },
  {
    id: 'review-6',
    fromUserId: 'helper-3',
    fromUserName: 'Priya S.',
    fromUserRole: 'helper',
    toUserId: 'elder-1',
    rating: 5,
    comment: 'Margaret has the most beautiful garden. Spending the afternoon pruning her roses was pure joy. She sent me home with fresh tomatoes!',
    service: 'garden',
    date: '2026-02-21',
  },
];

// ─── Message Threads ────────────────────────────────────────────────────────
export const messageThreads: MessageThread[] = [
  {
    id: 'thread-1',
    participantIds: ['elder-1', 'helper-1'],
    participantNames: ['Margaret Chen', 'Sarah Williams'],
    lastMessage: 'See you Wednesday at 10! I\'ll have the kettle on.',
    lastMessageTime: '2026-03-03T09:15:00Z',
    unreadCount: 0,
  },
  {
    id: 'thread-2',
    participantIds: ['elder-2', 'helper-2'],
    participantNames: ['Robert Patterson', 'James Okafor'],
    lastMessage: 'My appointment is at Lions Gate Hospital — I\'ll text the exact address.',
    lastMessageTime: '2026-03-03T08:45:00Z',
    unreadCount: 1,
  },
  {
    id: 'thread-3',
    participantIds: ['elder-3', 'helper-3'],
    participantNames: ['Dorothy Singh', 'Priya Sharma'],
    lastMessage: 'I bought extra basmati rice — should I bring my own spices too?',
    lastMessageTime: '2026-03-02T20:30:00Z',
    unreadCount: 2,
  },
  {
    id: 'thread-4',
    participantIds: ['elder-3', 'helper-5'],
    participantNames: ['Dorothy Singh', 'Mei Liu'],
    lastMessage: 'Thank you Mei. The spare room is all ready for you on Friday night.',
    lastMessageTime: '2026-03-03T07:00:00Z',
    unreadCount: 0,
  },
];

// ─── Current user references (for demo mode) ───────────────────────────────
export const currentElder = elders[0]; // Margaret Chen
export const currentHelper = helpers[0]; // Sarah Williams
