// Tend — Supabase database types
// This file will be auto-generated by running:
//   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/database.types.ts
//
// For now, we export a placeholder that matches our schema structure.
// Once a Supabase project is created, regenerate this file.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = 'elder' | 'helper' | 'family';
export type ServiceType =
  | 'companionship' | 'groceries' | 'meal_prep' | 'errands'
  | 'housekeeping' | 'transportation' | 'garden' | 'tech_help'
  | 'pet_care' | 'overnight';
export type BookingStatus = 'pending' | 'confirmed' | 'active' | 'completed' | 'cancelled';
export type GenderType = 'male' | 'female' | 'non_binary';
export type AgeGroup = '20-30' | '30-40' | '40-50' | '50-60' | '60-70';
export type VerificationLevel = 'basic' | 'enhanced' | 'premium';
export type VerificationCheckType =
  | 'id_passport' | 'id_drivers_license' | 'criminal_record_check'
  | 'criminal_record_review' | 'worksafebc_coverage' | 'pipa_consent'
  | 'first_aid' | 'reference_check';
export type VerificationStatus = 'cleared' | 'pending' | 'expired' | 'not_submitted';
export type VisitMood = 'great' | 'good' | 'okay' | 'low';
export type AlertSeverity = 'info' | 'warning' | 'urgent';
export type AlertType = 'missed_visit' | 'schedule_change' | 'helper_change' | 'wellness_note' | 'photo_shared';
export type CareTeamRole = 'primary' | 'backup';
export type ScheduleFrequency = 'weekly' | 'biweekly';
export type TripStatus = 'in_progress' | 'completed';

// Table row types (will be replaced by auto-generated types)
export interface ProfileRow {
  id: string;
  role: UserRole;
  first_name: string;
  last_name: string;
  street_address: string | null;
  city: string | null;
  province: string | null;
  postal_code: string | null;
  avatar_url: string | null;
  bio: string | null;
  created_at: string;
  updated_at: string;
}

export interface ElderProfileRow {
  id: string;
  rating: number;
  total_reviews: number;
  needs: ServiceType[];
  preferences: Json;
}

export interface HelperProfileRow {
  id: string;
  gender: GenderType | null;
  age_group: AgeGroup | null;
  headline: string | null;
  cover_photo_url: string | null;
  special_skills: string[];
  has_car: boolean;
  languages: string[];
  verification_level: VerificationLevel;
  id_verified: boolean;
  background_checked: boolean;
  references_verified: number;
  rating: number;
  total_reviews: number;
  repeat_clients: number;
  completed_bookings: number;
  response_time: string;
  availability: Json;
}

export interface FamilyProfileRow {
  id: string;
  relationship: string | null;
  linked_elder_id: string | null;
  notification_preferences: Json;
}

export interface BookingRow {
  id: string;
  elder_id: string;
  helper_id: string;
  service: ServiceType;
  date: string;
  start_time: string;
  end_time: string;
  duration: number;
  total_cost: number;
  status: BookingStatus;
  notes: string | null;
  elder_rating: number | null;
  helper_rating: number | null;
  created_at: string;
  updated_at: string;
}

export interface ReviewRow {
  id: string;
  from_user_id: string;
  to_user_id: string;
  from_user_role: UserRole;
  rating: number;
  comment: string | null;
  service: ServiceType;
  booking_id: string | null;
  created_at: string;
}

export interface MessageThreadRow {
  id: string;
  last_message: string | null;
  last_message_at: string | null;
  created_at: string;
}

export interface MessageRow {
  id: string;
  thread_id: string;
  sender_id: string;
  text: string;
  read: boolean;
  created_at: string;
}

export interface VisitNoteRow {
  id: string;
  booking_id: string | null;
  helper_id: string;
  elder_id: string;
  date: string;
  service: ServiceType;
  summary: string | null;
  mood: VisitMood | null;
  duration: number | null;
  created_at: string;
}

export interface FamilyAlertRow {
  id: string;
  family_id: string;
  elder_id: string;
  type: AlertType;
  title: string;
  description: string | null;
  severity: AlertSeverity;
  read: boolean;
  linked_booking_id: string | null;
  created_at: string;
}

export interface CareTeamMemberRow {
  id: string;
  elder_id: string;
  helper_id: string;
  role: CareTeamRole;
  services: ServiceType[];
  last_visit: string | null;
  created_at: string;
}

export interface RecurringScheduleRow {
  id: string;
  elder_id: string;
  primary_helper_id: string;
  backup_helper_id: string | null;
  service: ServiceType;
  day_of_week: string;
  start_time: string;
  end_time: string;
  frequency: ScheduleFrequency;
  is_active: boolean;
  started_date: string | null;
  total_sessions: number;
  created_at: string;
}

export interface VerificationRecordRow {
  id: string;
  helper_id: string;
  type: VerificationCheckType;
  status: VerificationStatus;
  verified_date: string | null;
  expiry_date: string | null;
  description: string | null;
  issuing_authority: string | null;
  document_storage_path: string | null;
  created_at: string;
}

export interface QualityScoreRow {
  helper_id: string;
  overall: number;
  punctuality: number;
  communication: number;
  task_completion: number;
  elder_satisfaction: number;
  first_visit_callback_completed: boolean;
  last_spot_check_date: string | null;
  escalation_contact_available: boolean;
  updated_at: string;
}

export interface TransportSafetyRow {
  helper_id: string;
  driver_verified: boolean;
  insurance_attested: boolean;
  insurance_expiry_date: string | null;
  vehicle_year: number | null;
  vehicle_make: string | null;
  wait_and_accompany_available: boolean;
  updated_at: string;
}

export interface CareBundleRow {
  id: string;
  name: string;
  tagline: string | null;
  description: string | null;
  icon: string | null;
  color: string | null;
  weekly_price: number | null;
  regular_price: number | null;
  savings_percent: number | null;
  popular: boolean;
  is_active: boolean;
  created_at: string;
}

export interface TripLogRow {
  id: string;
  booking_id: string | null;
  helper_id: string;
  pickup: string | null;
  destination: string | null;
  pickup_time: string | null;
  dropoff_time: string | null;
  duration: number | null;
  wait_and_accompany: boolean;
  status: TripStatus;
  created_at: string;
}
